function ark = bsmc_wrapper(penalty_factor, m, initial_samples, pressure)
    ark = bsmc(@bump, [0 10], [0 10], ...
            @(x,y) (penalty_factor*bump_penalty(x,y)), ...
            m, initial_samples, pressure, archive_new('single', 1));
